/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-08 02:41:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminPageProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/layout/footJs.jsp", Long.valueOf(1669182270000L));
    _jspx_dependants.put("/WEB-INF/views/layout/header.jsp", Long.valueOf(1670065363000L));
    _jspx_dependants.put("jar:file:/Users/DevRoot/Dropbox/ITHub%20Project/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITHubProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/layout/adminNav.jsp", Long.valueOf(1670439592000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667809742337L));
    _jspx_dependants.put("jar:file:/Users/DevRoot/Dropbox/ITHub%20Project/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITHubProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.js\" integrity=\"sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/line-awesome.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/line-awesome-font-awesome.min.css\">\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick-theme.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/responsive.css\">\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/httpRequest.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/summernote-bs4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/lang/summernote-ko-KR.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/summernote-bs4.css\">\n");
      out.write("<title>ITHub</title>\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/flatpickr.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrapper\">\r\n");
      out.write("		");
      out.write("\n");
      out.write("<header>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"header-data\">\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminMain.go\" title=\"\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/fabicon.png\" alt=\"\"></a>\n");
      out.write("			</div><!--logo end-->\n");
      out.write("			<div class=\"search-bar\">\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminMain.go\" method=\"get\" onsubmit=\"return check(this)\">\n");
      out.write("					<input type=\"hidden\" name=\"type\" value=\"boardContent\">\n");
      out.write("					<input type=\"hidden\" name=\"path\" value=\"main\">\n");
      out.write("					<input type=\"text\" name=\"word\" placeholder=\"검색어를 입력하세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.word }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" autocomplete=\"off\">\n");
      out.write("					<button type=\"submit\"><i class=\"la la-search\"></i></button>\n");
      out.write("				</form>\n");
      out.write("			</div><!--search-bar end-->\n");
      out.write("			<nav>\n");
      out.write("				<ul>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminMain.go\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon1.png\" alt=\"\"></span>\n");
      out.write("							Home\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminPageList?pType=0\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon2.png\" alt=\"\"></span>\n");
      out.write("							회사 페이지 관리\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminPageList?pType=1\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon3.png\" alt=\"\"></span>\n");
      out.write("							학교 페이지 관리\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminUserList\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon4.png\" alt=\"\"></span>\n");
      out.write("							회원 관리\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminJobList\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon5.png\" alt=\"\"></span>\n");
      out.write("							채용공고 관리\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</nav><!--nav end-->\n");
      out.write("			<div class=\"menu-btn\">\n");
      out.write("				<a href=\"#\" title=\"\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("			</div><!--menu-btn end-->\n");
      out.write("			<div class=\"user-account\">\n");
      out.write("				<div class=\"user-info\">\n");
      out.write("					<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.adminName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("					<i class=\"la la-sort-down\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"user-account-settingss\" id=\"users\">\n");
      out.write("					<h3 class=\"tc\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/logout\" title=\"\">Logout</a></h3>\n");
      out.write("				</div><!--user-account-settingss end-->\n");
      out.write("			</div>\n");
      out.write("		</div><!--header-data end-->\n");
      out.write("	</div>\n");
      out.write("</header><!--header end-->	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<section class=\"cover-sec\">\r\n");
      out.write("			");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"add-pic-box\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row no-gutters\">\r\n");
      out.write("						<div class=\"col-lg-12 col-sm-12\">					\r\n");
      out.write("							<div id=\"changeBackpic\">\r\n");
      out.write("								<label>Change Image</label>				\r\n");
      out.write("							</div>			\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("		<main>\r\n");
      out.write("			<div class=\"main-section\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"main-section-data\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-3\">\r\n");
      out.write("								<div class=\"main-left-sidebar\">\r\n");
      out.write("									<div class=\"user_profile\">\r\n");
      out.write("										<div class=\"user-pro-img\">\r\n");
      out.write("											");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											<div class=\"add-dp\" id=\"OpenImgUpload\">\r\n");
      out.write("												<input type=\"file\" id=\"file\">\r\n");
      out.write("												<label for=\"file\"><i class=\"fas fa-camera\"></i></label>												\r\n");
      out.write("											</div>\r\n");
      out.write("										</div><!--user-pro-img end-->\r\n");
      out.write("										<div class=\"user_pro_status\">\r\n");
      out.write("											<ul class=\"flw-status\">\r\n");
      out.write("												<li style=\"cursor: pointer;\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/follow/followerList?user=other&mp=p&cSeq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">\r\n");
      out.write("													<span>Followers</span>\r\n");
      out.write("													<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pFollower }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div><!--user_pro_status end-->\r\n");
      out.write("										<ul class=\"social_links\">\r\n");
      out.write("											<li><a href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pLink}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("													<i class=\"la la-globe\"></i>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pLink }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("												</a>\r\n");
      out.write("											</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div><!--user_profile end-->\r\n");
      out.write("								</div><!--main-left-sidebar end-->\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6\">\r\n");
      out.write("								<div class=\"main-ws-sec\">\r\n");
      out.write("									<div class=\"user-tab-sec\">\r\n");
      out.write("										<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("										<div class=\"star-descp\">\r\n");
      out.write("											<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pInfo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("											<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.iSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("											\r\n");
      out.write("										</div><!--star-descp end-->\r\n");
      out.write("										<div class=\"tab-feed\">\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li data-tab=\"feed-dd\" class=\"active\">\r\n");
      out.write("													<a href=\"#\" title=\"\">\r\n");
      out.write("														<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ic1.png\" alt=\"\">\r\n");
      out.write("														<span>Feed</span>\r\n");
      out.write("													</a>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li data-tab=\"info-dd\">\r\n");
      out.write("													<a href=\"#\" title=\"\">\r\n");
      out.write("														<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ic2.png\" alt=\"\">\r\n");
      out.write("														<span>Info</span>\r\n");
      out.write("													</a>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li data-tab=\"portfolio-dd\">\r\n");
      out.write("													<a href=\"#\" title=\"\">\r\n");
      out.write("														<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ic3.png\" alt=\"\">\r\n");
      out.write("														<span>Portfolio</span>\r\n");
      out.write("													</a>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div><!-- tab-feed end-->\r\n");
      out.write("									</div><!--user-tab-sec end-->\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"product-feed-tab current\" id=\"feed-dd\">\r\n");
      out.write("										<div class=\"posts-section\">\r\n");
      out.write("											<div class=\"post-bar\">\r\n");
      out.write("												<div class=\"post_topbar\">\r\n");
      out.write("													<div class=\"usy-dt\">\r\n");
      out.write("														<img src=\"images/resources/company-pic.png\" alt=\"\">\r\n");
      out.write("														<div class=\"usy-name\">\r\n");
      out.write("															<h3>Facebook Inc. 	</h3>\r\n");
      out.write("															<span><img src=\"images/clock.png\" alt=\"\">3 min ago</span>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"ed-opts\">\r\n");
      out.write("														<a href=\"#\" title=\"\" class=\"ed-opts-open\"><i class=\"la la-ellipsis-v\"></i></a>\r\n");
      out.write("														<ul class=\"ed-options\">\r\n");
      out.write("															<li><a href=\"#\" title=\"\">Edit Post</a></li>\r\n");
      out.write("															<li><a href=\"#\" title=\"\">Unsaved</a></li>\r\n");
      out.write("															<li><a href=\"#\" title=\"\">Unbid</a></li>\r\n");
      out.write("															<li><a href=\"#\" title=\"\">Close</a></li>\r\n");
      out.write("															<li><a href=\"#\" title=\"\">Hide</a></li>\r\n");
      out.write("														</ul>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"epi-sec\">\r\n");
      out.write("													<ul class=\"descp\">\r\n");
      out.write("														<li><img src=\"images/icon8.png\" alt=\"\"><span>Epic Coder</span></li>\r\n");
      out.write("														<li><img src=\"images/icon9.png\" alt=\"\"><span>India</span></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("													<ul class=\"bk-links\">\r\n");
      out.write("														<li><a href=\"#\" title=\"\"><i class=\"la la-bookmark\"></i></a></li>\r\n");
      out.write("														<li><a href=\"#\" title=\"\"><i class=\"la la-envelope\"></i></a></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"job_descp\">\r\n");
      out.write("													<h3>Senior UI / UX designer</h3>\r\n");
      out.write("													<ul class=\"job-dt\">\r\n");
      out.write("														<li><a href=\"#\" title=\"\">Full Time</a></li>\r\n");
      out.write("														<li><span>$30 / hr</span></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam luctus hendrerit metus, ut ullamcorper quam finibus at. Etiam id magna sit amet... <a href=\"#\" title=\"\">view more</a></p>\r\n");
      out.write("													<ul class=\"skill-tags\">\r\n");
      out.write("														<li><a href=\"#\" title=\"\">HTML</a></li>\r\n");
      out.write("														<li><a href=\"#\" title=\"\">PHP</a></li>\r\n");
      out.write("														<li><a href=\"#\" title=\"\">CSS</a></li>\r\n");
      out.write("														<li><a href=\"#\" title=\"\">Javascript</a></li>\r\n");
      out.write("														<li><a href=\"#\" title=\"\">Wordpress</a></li> 	\r\n");
      out.write("													</ul>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"job-status-bar\">\r\n");
      out.write("													<ul class=\"like-com\">\r\n");
      out.write("														<li>\r\n");
      out.write("															<a href=\"#\"><i class=\"fas fa-heart\"></i> Like</a>\r\n");
      out.write("															<img src=\"images/liked-img.png\" alt=\"\">\r\n");
      out.write("															<span>25</span>\r\n");
      out.write("														</li>\r\n");
      out.write("														<li><a href=\"#\" class=\"com\"><i class=\"fas fa-comment-alt\"></i> Comments 15</a></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("													<a href=\"#\"><i class=\"fas fa-eye\"></i>Views 50</a>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div><!--post-bar end-->\r\n");
      out.write("										</div><!--posts-section end-->\r\n");
      out.write("									</div><!--product-feed-tab end-->\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"product-feed-tab\" id=\"info-dd\">\r\n");
      out.write("										<div class=\"user-profile-ov\">\r\n");
      out.write("											<h3><a href=\"#\" title=\"\" class=\"overview-open\">Overview</a> <a href=\"#\" title=\"\" class=\"overview-open\"><i class=\"fa fa-pencil\"></i></a></h3>\r\n");
      out.write("											<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pText }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("										</div><!--user-profile-ov end-->\r\n");
      out.write("										<div class=\"user-profile-ov st2\">\r\n");
      out.write("											<h3><a href=\"#\" title=\"\" class=\"esp-bx-open\">Establish Since </a><a href=\"#\" title=\"\" class=\"esp-bx-open\"><i class=\"fa fa-pencil\"></i></a> <a href=\"#\" title=\"\" class=\"esp-bx-open\"><i class=\"fa fa-plus-square\"></i></a></h3>\r\n");
      out.write("											<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pFounddate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("										</div><!--user-profile-ov end-->\r\n");
      out.write("										<div class=\"user-profile-ov\">\r\n");
      out.write("											<h3><a href=\"#\" title=\"\" class=\"emp-open\">Total Employees</a> <a href=\"#\" title=\"\" class=\"emp-open\"><i class=\"fa fa-pencil\"></i></a> <a href=\"#\" title=\"\" class=\"emp-open\"><i class=\"fa fa-plus-square\"></i></a></h3>\r\n");
      out.write("											<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pEmpcnt }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("										</div><!--user-profile-ov end-->\r\n");
      out.write("										<div class=\"user-profile-ov\">\r\n");
      out.write("											<h3><a href=\"#\" title=\"\" class=\"lct-box-open\">Location</a> <a href=\"#\" title=\"\" class=\"lct-box-open\"><i class=\"fa fa-pencil\"></i></a> <a href=\"#\" title=\"\" class=\"lct-box-open\"><i class=\"fa fa-plus-square\"></i></a></h3>\r\n");
      out.write("											<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.cSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("											<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.ciSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("											<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pAddr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("										</div><!--user-profile-ov end-->\r\n");
      out.write("									</div><!--product-feed-tab end-->\r\n");
      out.write("									<div class=\"product-feed-tab\" id=\"portfolio-dd\">\r\n");
      out.write("										<div class=\"portfolio-gallery-sec\">\r\n");
      out.write("											<h3>Portfolio</h3>\r\n");
      out.write("											<div class=\"gallery_pf\">\r\n");
      out.write("												<div class=\"row\">\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img1.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img2.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img3.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img4.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img5.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img6.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img7.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img8.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img9.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-lg-4 col-md-4 col-sm-4 col-6\">\r\n");
      out.write("														<div class=\"gallery_pt\">\r\n");
      out.write("															<img src=\"images/resources/pf-img10.jpg\" alt=\"\">\r\n");
      out.write("															<a href=\"#\" title=\"\"><img src=\"images/all-out.png\" alt=\"\"></a>\r\n");
      out.write("														</div><!--gallery_pt end-->\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div><!--gallery_pf end-->\r\n");
      out.write("										</div><!--portfolio-gallery-sec end-->\r\n");
      out.write("									</div><!--product-feed-tab end-->\r\n");
      out.write("								</div><!--main-ws-sec end-->\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-3\">\r\n");
      out.write("								<div class=\"right-sidebar\">\r\n");
      out.write("									<div class=\"message-btn\">\r\n");
      out.write("										<a href=\"#\" title=\"\"><i class=\"fa fa-envelope\"></i> Message</a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"widget widget-portfolio\">\r\n");
      out.write("										<div class=\"wd-heady\">\r\n");
      out.write("											<h3>Portfolio</h3>\r\n");
      out.write("											<img src=\"images/photo-icon.png\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"pf-gallery\">\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery1.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery2.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery3.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery4.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery5.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery6.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery7.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery8.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery9.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery10.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery11.png\" alt=\"\"></a></li>\r\n");
      out.write("												<li><a href=\"#\" title=\"\"><img src=\"images/resources/pf-gallery12.png\" alt=\"\"></a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div><!--pf-gallery end-->\r\n");
      out.write("									</div><!--widget-portfolio end-->\r\n");
      out.write("								</div><!--right-sidebar end-->\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div><!-- main-section-data end-->\r\n");
      out.write("				</div> \r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("\r\n");
      out.write("		<footer>\r\n");
      out.write("			<div class=\"footy-sec mn no-margin\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"help-center.html\" title=\"\">Help Center</a></li>\r\n");
      out.write("						<li><a href=\"about.html\" title=\"\">About</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Privacy Policy</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Community Guidelines</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Cookies Policy</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Career</a></li>\r\n");
      out.write("						<li><a href=\"forum.html\" title=\"\">Forum</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Language</a></li>\r\n");
      out.write("						<li><a href=\"#\" title=\"\">Copyright Policy</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<p><img src=\"images/copy-icon2.png\" alt=\"\">Copyright 2018</p>\r\n");
      out.write("					<img class=\"fl-rgt\" src=\"images/logo2.png\" alt=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer><!--footer end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"overview-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Overview</h3>\r\n");
      out.write("				<span>5000 character left</span>\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/update\" name=\"update\" method=\"post\">\r\n");
      out.write("					<textarea id=\"pText\" name=\"pText\"></textarea>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"experience-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Experience</h3>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"subject\" placeholder=\"Subject\">\r\n");
      out.write("					<textarea></textarea>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"save-add\">Save & Add More</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"education-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Education</h3>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"school\" placeholder=\"School / University\">\r\n");
      out.write("					<div class=\"datepicky\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-6 no-left-pd\">\r\n");
      out.write("								<div class=\"datefm\">\r\n");
      out.write("									<input type=\"text\" name=\"from\" placeholder=\"From\" class=\"datepicker\">	\r\n");
      out.write("									<i class=\"fa fa-calendar\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-lg-6 no-righ-pd\">\r\n");
      out.write("								<div class=\"datefm\">\r\n");
      out.write("									<input type=\"text\" name=\"to\" placeholder=\"To\" class=\"datepicker\">\r\n");
      out.write("									<i class=\"fa fa-calendar\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"degree\" placeholder=\"Degree\">\r\n");
      out.write("					<textarea placeholder=\"Description\"></textarea>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"save-add\">Save & Add More</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"location-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Location</h3>\r\n");
      out.write("				<form>\r\n");
      out.write("					<div class=\"datefm\">\r\n");
      out.write("						<select>\r\n");
      out.write("							<option>Country</option>\r\n");
      out.write("							<option value=\"pakistan\">Pakistan</option>\r\n");
      out.write("							<option value=\"england\">England</option>\r\n");
      out.write("							<option value=\"india\">India</option>\r\n");
      out.write("							<option value=\"usa\">United Sates</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<i class=\"fa fa-globe\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"datefm\">\r\n");
      out.write("						<select>\r\n");
      out.write("							<option>City</option>\r\n");
      out.write("							<option value=\"london\">London</option>\r\n");
      out.write("							<option value=\"new-york\">New York</option>\r\n");
      out.write("							<option value=\"sydney\">Sydney</option>\r\n");
      out.write("							<option value=\"chicago\">Chicago</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"skills-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Skills</h3>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\" title=\"\" class=\"skl-name\">HTML</a><a href=\"#\" title=\"\" class=\"close-skl\"><i class=\"la la-close\"></i></a></li>\r\n");
      out.write("					<li><a href=\"#\" title=\"\" class=\"skl-name\">php</a><a href=\"#\" title=\"\" class=\"close-skl\"><i class=\"la la-close\"></i></a></li>\r\n");
      out.write("					<li><a href=\"#\" title=\"\" class=\"skl-name\">css</a><a href=\"#\" title=\"\" class=\"close-skl\"><i class=\"la la-close\"></i></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"skills\" placeholder=\"Skills\">\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"save-add\">Save & Add More</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"create-portfolio\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Create Portfolio</h3>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"pf-name\" placeholder=\"Portfolio Name\">\r\n");
      out.write("					<div class=\"file-submit nomg\">\r\n");
      out.write("						<input type=\"file\" name=\"file\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"pf-img\">\r\n");
      out.write("						<img src=\"images/resources/np.png\" alt=\"\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"text\" name=\"website-url\" placeholder=\"htp://www.example.com\">\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"establish-box\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Establish Since</h3>\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/update\" name=\"update\" method=\"post\">\r\n");
      out.write("					<div class=\"daty\">\r\n");
      out.write("						<input type=\"date\" name=\"establish\" placeholder=\"Select Date\" class=\"datepicker\">\r\n");
      out.write("						<i class=\"fa fa-calendar\"></i>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"total-employes\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Total Employees</h3>\r\n");
      out.write("				<form>\r\n");
      out.write("					<input type=\"text\" name=\"employes\" placeholder=\"Type in numbers\">\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"submit\" class=\"cancel\">Cancel</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"overview-box\" id=\"changeBack-pic\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Change BackImage</h3>\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/backPic\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<input type=\"hidden\" name=\"pSeq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("					<input type=\"file\" name=\"backPic\" size=\"400\"/>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"reset\" class=\"cancel\">Reset</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"overview-box\" id=\"change-image\">\r\n");
      out.write("			<div class=\"overview-edit\">\r\n");
      out.write("				<h3>Change ProfileImage</h3>\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/pPic\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<input type=\"hidden\" name=\"pSeq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pSeq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("					<input type=\"file\" name=\"logo\" size=\"400\"/>\r\n");
      out.write("					<button type=\"submit\" class=\"save\">Save</button>\r\n");
      out.write("					<button type=\"reset\" class=\"cancel\">Reset</button>\r\n");
      out.write("				</form>\r\n");
      out.write("				<a href=\"#\" title=\"\" class=\"close-box\"><i class=\"la la-close\"></i></a>\r\n");
      out.write("			</div><!--overview-edit end-->\r\n");
      out.write("		</div><!--overview-box end-->\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/layout/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/layout/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/layout/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/admin/adminPageProfile.jsp(13,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pBackpic == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/resources/cover-img.jpg\" alt=\"\">\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<img width=\"1600px\" height=\"400px\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pBackpic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"???\">\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("												");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/admin/adminPageProfile.jsp(44,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pPic == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/images/resources/cover-img.jpg\" alt=\"\">\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("													<img height=\"180px\" width=\"180px\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page.pPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"어디갔노\">\r\n");
          out.write("												");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
