/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-07 08:17:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/layout/footJs.jsp", Long.valueOf(1669182270000L));
    _jspx_dependants.put("/WEB-INF/views/layout/header.jsp", Long.valueOf(1670065363000L));
    _jspx_dependants.put("/WEB-INF/views/layout/navbar.jsp", Long.valueOf(1670227684000L));
    _jspx_dependants.put("jar:file:/Users/DevRoot/Dropbox/ITHub%20Project/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITHubProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1667809742337L));
    _jspx_dependants.put("jar:file:/Users/DevRoot/Dropbox/ITHub%20Project/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ITHubProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/layout/footer.jsp", Long.valueOf(1670396629000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.js\" integrity=\"sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/line-awesome.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/line-awesome-font-awesome.min.css\">\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font-awesome.min.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick-theme.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/responsive.css\">\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/httpRequest.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/summernote-bs4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/lang/summernote-ko-KR.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/summernote/summernote-bs4.css\">\n");
      out.write("<title>ITHub</title>\n");
      out.write("\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.mCustomScrollbar.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\" integrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function check(f){\n");
      out.write("	if(f.boardContent.value == \"\"){\n");
      out.write("		alert(\"내용을 입력하세요\");\n");
      out.write("		f.boardContent.focus();\n");
      out.write("		return false;\n");
      out.write("	} else if (f.boardOpen.value == \"\"){\n");
      out.write("		alert(\"게시글 공개 여부를 선택하세요\");\n");
      out.write("		return false;\n");
      out.write("	}  else if (f.boardPossible.value == \"\"){\n");
      out.write("		alert(\"댓글 가능 여부를 선택하세요\");\n");
      out.write("		return false;\n");
      out.write("	} else {\n");
      out.write("		return true;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write(".radio {\n");
      out.write("	padding-left: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<body>	\n");
      out.write("	<div class=\"wrapper\">	\n");
      out.write("		");
      out.write("\n");
      out.write("<header>\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"header-data\">\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" title=\"\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/fabicon.png\" alt=\"\"></a>\n");
      out.write("			</div><!--logo end-->\n");
      out.write("			<div class=\"search-bar\">\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list?path=main\" method=\"get\" onsubmit=\"return check(this)\">\n");
      out.write("					<input type=\"hidden\" name=\"type\" value=\"boardContent\">\n");
      out.write("					<input type=\"hidden\" name=\"path\" value=\"main\">\n");
      out.write("					<input type=\"text\" name=\"word\" placeholder=\"검색어를 입력하세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.word }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" autocomplete=\"off\">\n");
      out.write("					<button type=\"submit\"><i class=\"la la-search\"></i></button>\n");
      out.write("				</form>\n");
      out.write("			</div><!--search-bar end-->\n");
      out.write("			<nav>\n");
      out.write("				<ul>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon1.png\" alt=\"\"></span>\n");
      out.write("							Home\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/pageList?pType=0\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon2.png\" alt=\"\"></span>\n");
      out.write("							Companies\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/pageList?pType=1\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon3.png\" alt=\"\"></span>\n");
      out.write("							University\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/userList\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon4.png\" alt=\"\"></span>\n");
      out.write("							Profiles\n");
      out.write("						</a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/userList\" title=\"\">User Profile</a></li>\n");
      out.write("							<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/profile\" title=\"\">My Profile</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/job/jobList\" title=\"\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon5.png\" alt=\"\"></span>\n");
      out.write("							Jobs\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\" title=\"\" class=\"not-box-openm\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon6.png\" alt=\"\"></span>\n");
      out.write("							Messages\n");
      out.write("						</a>\n");
      out.write("						<div class=\"notification-box msg\" id=\"message\">\n");
      out.write("							<div class=\"nt-title\">\n");
      out.write("								<h4>Setting</h4>\n");
      out.write("								<a href=\"#\" title=\"\">Clear all</a>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"nott-list\">\n");
      out.write("								<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img1.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"messages.html\" title=\"\">Jassica William</a> </h3>\n");
      out.write("					  					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</p>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img2.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"messages.html\" title=\"\">Jassica William</a></h3>\n");
      out.write("					  					<p>Lorem ipsum dolor sit amet.</p>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img3.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"messages.html\" title=\"\">Jassica William</a></h3>\n");
      out.write("					  					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo incididunt ut labore et dolore magna aliqua.</p>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"view-all-nots\">\n");
      out.write("				  					<a href=\"messages.html\" title=\"\">View All Messsages</a>\n");
      out.write("				  				</div>\n");
      out.write("							</div><!--nott-list end-->\n");
      out.write("						</div><!--notification-box end-->\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"#\" title=\"\" class=\"not-box-open\">\n");
      out.write("							<span><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/icon7.png\" alt=\"\"></span>\n");
      out.write("							Notification\n");
      out.write("						</a>\n");
      out.write("						<div class=\"notification-box noti\" id=\"notification\">\n");
      out.write("							<div class=\"nt-title\">\n");
      out.write("								<h4>Setting</h4>\n");
      out.write("								<a href=\"#\" title=\"\">Clear all</a>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"nott-list\">\n");
      out.write("								<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img1.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"#\" title=\"\">Jassica William</a> Comment on your project.</h3>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img2.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"#\" title=\"\">Jassica William</a> Comment on your project.</h3>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img3.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"#\" title=\"\">Jassica William</a> Comment on your project.</h3>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"notfication-details\">\n");
      out.write("					  				<div class=\"noty-user-img\">\n");
      out.write("					  					<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/resources/ny-img2.png\" alt=\"\">\n");
      out.write("					  				</div>\n");
      out.write("					  				<div class=\"notification-info\">\n");
      out.write("					  					<h3><a href=\"#\" title=\"\">Jassica William</a> Comment on your project.</h3>\n");
      out.write("					  					<span>2 min ago</span>\n");
      out.write("					  				</div><!--notification-info -->\n");
      out.write("				  				</div>\n");
      out.write("				  				<div class=\"view-all-nots\">\n");
      out.write("				  					<a href=\"#\" title=\"\">View All Notification</a>\n");
      out.write("				  				</div>\n");
      out.write("							</div><!--nott-list end-->\n");
      out.write("						</div><!--notification-box end-->\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</nav><!--nav end-->\n");
      out.write("			<div class=\"menu-btn\">\n");
      out.write("				<a href=\"#\" title=\"\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("			</div><!--menu-btn end-->\n");
      out.write("			<div class=\"user-account\">\n");
      out.write("				<div class=\"user-info\">\n");
      out.write("					<img height=\"30px\" width=\"30px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.mPic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\">\n");
      out.write("					<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.mFirstname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("					<i class=\"la la-sort-down\"></i>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"user-account-settingss\" id=\"users\">\n");
      out.write("					<h3>Online Status</h3>\n");
      out.write("					<ul class=\"on-off-status\">\n");
      out.write("						<li>\n");
      out.write("							<div class=\"fgt-sec\">\n");
      out.write("								<input type=\"radio\" name=\"cc\" id=\"c5\">\n");
      out.write("								<label for=\"c5\">\n");
      out.write("									<span></span>\n");
      out.write("								</label>\n");
      out.write("								<small>Online</small>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<div class=\"fgt-sec\">\n");
      out.write("								<input type=\"radio\" name=\"cc\" id=\"c6\">\n");
      out.write("								<label for=\"c6\">\n");
      out.write("									<span></span>\n");
      out.write("								</label>\n");
      out.write("								<small>Offline</small>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("					<h3>Custom Status</h3>\n");
      out.write("					<div class=\"search_form\">\n");
      out.write("						<form>\n");
      out.write("							<input type=\"text\" name=\"search\">\n");
      out.write("							<button type=\"submit\">Ok</button>\n");
      out.write("						</form>\n");
      out.write("					</div><!--search_form end-->\n");
      out.write("					<h3>Setting</h3>\n");
      out.write("					<ul class=\"us-links\">\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/accountSetting\" title=\"\">Account Setting</a></li>\n");
      out.write("						<li><a href=\"#\" title=\"\">Privacy</a></li>\n");
      out.write("						<li><a href=\"#\" title=\"\">Faqs</a></li>\n");
      out.write("						<li><a href=\"#\" title=\"\">Terms & Conditions</a></li>\n");
      out.write("						<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/page/pageForm\" title=\"\">Create a Page</a>\n");
      out.write("					</ul>\n");
      out.write("					<h3 class=\"tc\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout\" title=\"\">Logout</a></h3>\n");
      out.write("				</div><!--user-account-settingss end-->\n");
      out.write("			</div>\n");
      out.write("		</div><!--header-data end-->\n");
      out.write("	</div>\n");
      out.write("</header><!--header end-->	");
      out.write("\n");
      out.write("		<section class=\"profile-account-setting\">\n");
      out.write("			<div class=\"container\">\n");
      out.write("				<div class=\"account-tabs-setting\">\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-lg-12\">\n");
      out.write("							<div class=\"tab-content\" id=\"nav-tabContent\">\n");
      out.write("							  	<div class=\"tab-pane fade active show\" id=\"nav-deactivate\" role=\"tabpanel\" aria-labelledby=\"nav-deactivate-tab\">\n");
      out.write("							  		<div class=\"acc-setting\">\n");
      out.write("										<h3>게시글 작성</h3>\n");
      out.write("										\n");
      out.write("										<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/write\" method=\"post\" onsubmit=\"return check(this)\" enctype=\"multipart/form-data\">\n");
      out.write("											<input type=\"hidden\" name=\"path\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("											<div class=\"cp-field\">\n");
      out.write("												<h5>내용</h5>\n");
      out.write("												<textarea id=\"summernote\" class=\"summernote\" name=\"boardContent\"></textarea>\n");
      out.write("											</div>\n");
      out.write("\n");
      out.write("											<div class=\"cp-field\">\n");
      out.write("												<h5>게시글 공개 여부</h5>\n");
      out.write("											</div>\n");
      out.write("											\n");
      out.write("											<div class=\"radio\">\n");
      out.write("												<input type=\"radio\" name=\"boardOpen\" value=\"0\">&nbsp;전체 공개\n");
      out.write("												<input type=\"radio\" name=\"boardOpen\" value=\"1\">&nbsp;친구만 공개\n");
      out.write("												<input type=\"radio\" name=\"boardOpen\" value=\"2\">&nbsp;나만 보기\n");
      out.write("											</div>\n");
      out.write("\n");
      out.write("											<div class=\"cp-field\">\n");
      out.write("												<h5>댓글 가능 여부</h5>\n");
      out.write("											</div>\n");
      out.write("											\n");
      out.write("											<div class=\"radio\">\n");
      out.write("												<input type=\"radio\" name=\"boardPossible\" value=\"0\">&nbsp;전체\n");
      out.write("												<input type=\"radio\" name=\"boardPossible\" value=\"1\">&nbsp;친구만\n");
      out.write("												<input type=\"radio\" name=\"boardPossible\" value=\"2\">&nbsp;차단\n");
      out.write("											</div>\n");
      out.write("											\n");
      out.write("											<div class=\"cp-field\">\n");
      out.write("												<h5>첨부 파일</h5>\n");
      out.write("												<div class=\"cpp-fiel\">\n");
      out.write("													<input type=\"file\" name=\"file\" size=\"400\">\n");
      out.write("												</div>\n");
      out.write("											</div>\n");
      out.write("											\n");
      out.write("											<div class=\"save-stngs pd3\">\n");
      out.write("												<ul>\n");
      out.write("													<li><button type=\"submit\">게시글 올리기</button></li>\n");
      out.write("													<li><button type=\"reset\">초기화</button></li>\n");
      out.write("												</ul>\n");
      out.write("											</div><!--save-stngs end-->\n");
      out.write("										</form>\n");
      out.write("									</div><!--acc-setting end-->\n");
      out.write("							  	</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div><!--account-tabs-setting end-->\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("		\n");
      out.write("		");
      out.write("\n");
      out.write("<div class=\"footy-sec\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<ul>\n");
      out.write("			<li><a href=\"#\" title=\"\">Help Center</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">About</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Privacy Policy</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Community Guidelines</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Cookies Policy</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Career</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Forum</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Language</a></li>\n");
      out.write("			<li><a href=\"#\" title=\"\">Copyright Policy</a></li>\n");
      out.write("		</ul>\n");
      out.write("		<p><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("images/copy-icon.png\" alt=\"\">Copyright 2022</p>\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/adminLogin\" style=\"color: #E75348;\">adminGOOOO</a>\n");
      out.write("	</div>\n");
      out.write("</div><!--footy-sec end-->");
      out.write("\n");
      out.write("\n");
      out.write("	</div><!--theme-layout end-->\n");
      out.write("    <script>\n");
      out.write("    $('#summernote').summernote({\n");
      out.write("        tabsize: 2,\n");
      out.write("        height: 400\n");
      out.write("      });\n");
      out.write("    </script>\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.mCustomScrollbar.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/slick/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/popper.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/layout/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/layout/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/layout/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
